export const SERIAL_PROFILES_CONFIG_ENV = "PI_DEVICES_SERIAL_PROFILES_CONFIG";
export const SERIAL_CREDENTIAL_SERVICE_ENV = "PI_DEVICES_SERIAL_CREDENTIAL_SERVICE";
export const DEFAULT_SERIAL_CREDENTIAL_SERVICE = "pi-devices.serial";
